language: node_js

node_js:
- '6'

env:
- VERSION="1.0.0-snapshot"

install:
- npm install

script:
- npm run build

after_success:
- openssl aes-256-cbc -K $encrypted_c792ecfbc4b2_key -iv $encrypted_c792ecfbc4b2_iv -in deploy/key.enc -out deploy/key -d
- deploy/deploy.sh
