language: node_js

node_js:
- '6'

env:
- VERSION="1.0.0-snapshot"

install:
- npm install

script:
- npm run build

deploy:
  provider: script
  script: deploy/deploy.sh
  skip_cleanup: true
  on:
    repo: G-Node/gnode-bootstrap-theme
    branch: master
